---
title: "MAGMA_celltyping"
author: "Eric Zillich"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#load packages
library(dplyr)
library(MAGMA.Celltyping)
```


## MAGMA output files for GWASs (.out, .raw)

```{r importGWAS}
# path/to/results/scDRS/

ctd <- ewceData::ctd()


```

# Perform scDRS munge

```{r scDRS munge}
# $ scdrs munge-gs --out-file /path/to/results/scDRS/SUDs_munge_Psych.gs --pval-file /path/to/results/scDRS/pval_SUDs_Psych.tsv --weight zscore --n-max 1000
 
```

# Import seurat object and convert to h5ad file

```{r importObject}
rm(list=ls())

seurat <- readRDS(file = "/path/to/data/6_LinkedPeaks.rds")
DefaultAssay(seurat) <- "RNA"

# Remove ATAC assay and scale.data slot otherwise scDRS will report errors
seurat2 <- DietSeurat(
  seurat,
  counts = TRUE,
  data = TRUE,
  scale.data = FALSE,
  assays = "RNA",
  dimreducs = NULL,
  graphs = NULL,
  misc = F
)

## Convert to h5ad

SaveH5Seurat(seurat2, filename = "/path/to/data/scDRS/6_LinkedPeaks.h5Seurat")

Convert("/path/to/data/scDRS/6_LinkedPeaks.h5Seurat", dest = "/path/to/data/scDRS/6_LinkedPeaks.h5Seurat.h5ad")
```

# Run scDRS main (score) function

```{r scdrs score}
# scdrs compute-score\
#     --h5ad-file /path/to/data/scDRS/6_LinkedPeaks.h5Seurat.h5ad\
#     --h5ad-species human\
#     --gs-file /path/to/results/scDRS/SUDs_munge_Psych.gs\
#     --gs-species human\
#     --out-folder /path/to/results/scDRS/\
#     --flag-filter-data True\
#     --adj_prop celltypes\
#     --flag-raw-count True\
#     --n-ctrl 1000\
#     --flag-return-ctrl-raw-score False\
#     --flag-return-ctrl-norm-score True

```

## Run scDRS downstream analyses

```{r scDRS downstream}
## CUD

# scdrs perform-downstream\
#     --h5ad-file /path/to/data/scDRS/6_LinkedPeaks.h5Seurat.h5ad\
#     --score-file /path/to/results/scDRS/P_CUD.full_score.gz\
#     --out-folder /path/to/results/scDRS/downstream/\
#     --group-analysis celltypes\
#     --gene-analysis\
#     --flag-filter-data True\
#     --flag-raw-count True

# AUD
# scdrs perform-downstream\
#     --h5ad-file /path/to/data/scDRS/6_LinkedPeaks.h5Seurat.h5ad\
#     --score-file /path/to/results/scDRS/P_AUD.full_score.gz\
#     --out-folder /path/to/results/scDRS/downstream/\
#     --group-analysis celltypes\
#     --gene-analysis\
#     --flag-filter-data True\
#     --flag-raw-count True

#CanUD
# scdrs perform-downstream\
#     --h5ad-file /path/to/data/scDRS/6_LinkedPeaks.h5Seurat.h5ad\
#     --score-file /path/to/results/scDRS/P_CanUD.full_score.gz\
#     --out-folder /path/to/results/scDRS/downstream/\
#     --group-analysis celltypes\
#     --gene-analysis\
#     --flag-filter-data True\
#     --flag-raw-count True

#OUD
# scdrs perform-downstream\
#     --h5ad-file /path/to/data/scDRS/6_LinkedPeaks.h5Seurat.h5ad\
#     --score-file /path/to/results/scDRS/P_OUD.full_score.gz\
#     --out-folder /path/to/results/scDRS/downstream/\
#     --group-analysis celltypes\
#     --gene-analysis\
#     --flag-filter-data True\
#     --flag-raw-count True

#Smoking
# scdrs perform-downstream\
#     --h5ad-file /path/to/data/scDRS/6_LinkedPeaks.h5Seurat.h5ad\
#     --score-file /path/to/results/scDRS/P_Smoking.full_score.gz\
#     --out-folder /path/to/results/scDRS/downstream/\
#     --group-analysis celltypes\
#     --gene-analysis\
#     --flag-filter-data True\
#     --flag-raw-count True

#SCZ
# scdrs perform-downstream\
#     --h5ad-file /path/to/data/scDRS/6_LinkedPeaks.h5Seurat.h5ad\
#     --score-file /path/to/results/scDRS/P_SCZ.full_score.gz\
#     --out-folder /path/to/results/scDRS/downstream/\
#     --group-analysis celltypes\
#     --gene-analysis\
#     --flag-filter-data True\
#     --flag-raw-count True

#Height
# scdrs perform-downstream\
#     --h5ad-file /path/to/data/scDRS/6_LinkedPeaks.h5Seurat.h5ad\
#     --score-file /path/to/results/scDRS/P_Height.full_score.gz\
#     --out-folder /path/to/results/scDRS/downstream/\
#     --group-analysis celltypes\
#     --gene-analysis\
#     --flag-filter-data True\
#     --flag-raw-count True
```
